services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - uploads_data:/var/www/uploads:ro
      - /opt/recipe/dist:/var/www/recipe_src:ro
      - ./chess:/var/www/chess:ro
    environment:
      - GEMINI_API_KEY
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-web
    volumes:
      - uploads_data:/app/public/uploads
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "npx prisma db push && node prisma/seed.js && npm run start"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://blog_user:123166.@db:5432/blog_db?schema=public&connection_limit=10&pool_timeout=20&connect_timeout=60
      - REDIS_URL=redis://redis:6379
      - SKIP_BUILD_STATIC_GENERATION=true
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD:-}

  db:
    image: postgres:16-alpine
    container_name: blog-db
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=123166.
      - POSTGRES_DB=blog_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: blog-redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build: .
    container_name: blog-worker
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "npx prisma generate && node worker/publisher.js"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:-postgresql://blog_user:123166.@db:5432/blog_db?schema=public}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}

volumes:
  pgdata:
  redis_data:
  uploads_data:
