version: "3.8"
services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    container_name: blogs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass_2024
      POSTGRES_DB: blogs_cms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blogs_cms"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  postgres_data: